Establish a working provisioning script and gnome installer

diff --git a/provision b/provision
--- a/provision
+++ b/provision
@@ -1,34 +1,14 @@
 #!/bin/bash
 
-# TODO: Add steps to run `doom sync`
-# TODO: Add steps for choosing _deskmod to utilize
+source ./helpers
 
-spinner_pid=
 host_font_dir="$HOME/.local/share/fonts"
 host_org_notes_dir="$HOME/notes/tome"
 host_work_dirs=("$HOME/work/priming" "$HOME/work/sandbox" "$HOME/work/projects")
 stow_font_dir="fonts"
 non_base_config=("_deskmod" ".git" "$stow_font_dir" "emacs")
 
-function start_spinner {
-    set +m
-    echo -en "$1          "
-    { while : ; do for X in '  .     ' '   .    ' '    .   ' '     .  ' '      . ' '     .  ' '    .   ' '   .    ' '  .     ' ' .      ' ; do echo -en "\b\b\b\b\b\b\b\b$X" ; sleep 0.1 ; done ; done & } 2>/dev/null
-    spinner_pid=$!
-}
-
-function stop_spinner {
-    { kill -9 $spinner_pid && wait; } 2>/dev/null
-    set -m
-    echo -e "\n"
-    #echo -en "\033[2K\r"
-}
-
-function spinner {
-    start_spinner "$1"
-    sleep 1.5
-    stop_spinner
-}
+declare -a de=()
 
 if [[ $EUID -eq 0 ]]; then
     printf "Please run as normal user.\n" >&2
@@ -50,7 +30,7 @@ for dir in */; do
     dir=$(echo "$dir" | sed 's/\/*$//g')
     if [[ ! ${non_base_config[@]} =~ $dir ]]; then
         echo "Stowing configurations for $dir..."
-        stow "$dir"
+        stow -vv "$dir"
     fi
 done
 
@@ -58,12 +38,11 @@ spinner "\nCreating fonts directory... "
 mkdir -p "$host_font_dir"
 echo -e "Font directory created at: $host_font_dir"
 spinner "\nInitiating fonts stow and installation... "
-for dir in "$stow_font_dir"/*/; do
-    dir=${dir%*/}
-    dir=${dir##*/}
+for dir in "$stow_font_dir"/*; do
+    dir=$(basename $dir)
 
     echo "Stowing font $dir..."
-    stow -d "$stow_font_dir" -S "$dir" -t "$host_font_dir"
+    stow -vv -d "$stow_font_dir" -S "$dir" -t "$host_font_dir"
 done
 echo -e "\r"
 fc-cache -fv
@@ -78,7 +57,7 @@ for v in "${host_work_dirs[@]}"; do
     echo -e "Work directory created at: $v"
 done
 
-spinner "Detecting if yay is installed... "
+spinner "\nDetecting if yay is installed... "
 
 if ! command -v yay &> /dev/null; then
     spinner "\nInitiating installation of yay... "
@@ -100,40 +79,37 @@ stop_spinner
 
 yay -Syu --needed --noconfirm - < packages_base.txt
 
-exit 1
-
-gnome_shell_dir="$HOME/.local/share/gnome-shell"
-gnome_extensions_dir="$gnome_shell_dir/extensions"
-
-echo "Installing the following packages for gnome..."
-cat ./gnome_packages.txt
-
-sleep 5
-
-yay -Syu --needed --noconfirm - < ./gnome_packages.txt
-
-if [[ ! -d "$gnome_extensions_dir" ]]; then
-    echo "Creating extensions directory: $gnome_extensions_dir"
-    ln -s "$(pwd)/extensions" "$gnome_extensions_dir"
-fi
-
-echo -e "Establishing gnome configurations...\n"
-dconf load / < ./gnome-config
-
-echo -e "Removing special keybinds...\n"
-gsettings set org.gnome.settings-daemon.plugins.media-keys rotate-video-lock-static "[]"
-
-for f in ./extensions/*; do
-    if [[ -d "$f" ]]; then
-        extension=$(basename "$f")
-        echo "Enabling extension $extension..."
-        #gnome-extensions enable "$extension"
-    fi
-done
+spinner "\nInitializing installation of application plugins... "
 
 # Install VIM plugins
+echo -e "Installing VIM plugins...\n"
 vim +'PlugInstall --sync' +qa
 
 # Install tmux plugins
+echo -e "Installing tmux plugins...\n"
 ~/.tmux/plugins/tpm/scripts/install_plugins.sh
 
+# Install doom emacs
+echo -e "\nInstalling doom emacs...\n"
+doom sync
+
+spinner "\nInitializing desktop environment installation... "
+
+PS3="Select environment to install: "
+
+for e in _deskmod/*; do
+    e="$(basename $e)"
+    de+=("$e")
+done
+
+select c in "${de[@]}"; do
+    [[ -n $c ]] || { echo "Invalid choice. Please try again." >&2; continue; }
+    break # valid choice was made; exit prompt.
+done
+
+spinner "\nInitializing installation for $c... "
+
+spinner "Stowing configurations for $c... "
+stow -vv -R -d ./_deskmod -S "$c" -t $HOME
+
+"./_deskmod/$c/install.sh"
